# 난수

## #01. 작업준비

### 패키지 참조

In [1]:
import tensorflow as tf

## #02. 균등 분포 난수

일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 $x$가 각 예상되는 범위별로 균등한 확률로 일어날 것이라고 예상될 때 사용.

### 1) 균등 분포 난수의 사용 예

#### 주사위에 대한 확률

- 200번을 던지고 201번째  주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지 결과값에 영향을 받지 않는다.
- 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며 이는 앞의 1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.
- 이처럼 미래 결과값이 경험적으로 알 수 없을 상황에서 사용하는 것이 균등분포이다.

### 2) 균등 분포 난수 실험

#### 스칼라 형태의 균등 분포 난수

In [7]:
uni_rnd1 = tf.random.uniform(shape=[], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd1)

71


#### 백터 형태의 균등 분포 난수

In [13]:
uni_rnd2 = tf.random.uniform(shape=[5], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd2)

[77 31 63 23 18]


#### 행렬 형태의 균등 분포 난수

In [17]:
uni_rnd3 = tf.random.uniform(shape=[2,3], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd3)

[[96 40 31]
 [95 64 3]]


#### 텐서 형태의 균등 분포 난수

In [24]:
uni_rnd4 = tf.random.uniform(shape=[2,3,4], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd4)

[[[27 64 2 95]
  [22 68 84 10]
  [66 62 28 56]]

 [[96 97 60 31]
  [11 44 47 73]
  [50 26 40 35]]]


### 3) 렌덤값을 갖는 행렬 곱 예시

#### 랜덤값을 갖는 3행2열의 행렬을 변수 x로 정의

In [29]:
x = tf.Variable(tf.random.uniform([3, 2]))
tf.print(x)

[[0.134441257 0.0451544523]
 [0.800297618 0.49747932]
 [0.364748716 0.689677715]]


#### 랜덤값을 갖는 2행1열의 행렬을 변수 y로 정의

In [32]:
y = tf.Variable(tf.random.uniform([2, 1]))
tf.print(y)

[[0.861193538]
 [0.117126822]]


#### 행렬곱에 대한 연산을 수행하는 노드 정의

In [34]:
expr = tf.matmul(x, y)
tf.print(expr)

[[0.121068738]
 [0.74747932]
 [0.394899]]


## #03. 정규 분포 난수

정규분포란 과거의 축적된 경험적 데이터를 이미 보유하고 있는 상태에서 이용하여 미래에 발생할 결과값 $x$의 각 예상되는 범위별로 발생될 확률을 어느 정도 추정할 수 있을 때 사용

### 1) 정규 분포 난수의 사용 예

#### 매장의 매출액 예측

- 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백원 발생한 경우 평균이나 범위에 대한 예측이 가능하다.
- **`평균`에 대한 예측** → 이번달 매출은 과거 3개월의 매출평균인 2천백만원으로 예측.
- **`범위`에 대한 예측** → 최소 2천만원 ~  최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함.

#### 로또 추첨

- 64개의 공 중에서 하나를 랜덤으로 추출하면, 두 번째 랜덤 범위는 첫 번째 추출된 공을 제외한 범위 안에서 생성된다.
- 만약 로또 추첨시 하나의 공을 뽑아 번호를 확인하고 그 공을 다시 추첨 대상에 포함시켰다면 균등분포 난수가 된다.

### 2) 정규 분포 난수 실험

정규 분포 난수를 생성할 때는 평균(mean)과 표준편차(stddev)를 지정해야 한다.

#### 스칼라 형태의 정규 분포 난수

In [36]:
normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

0.566397071


#### 백터 형태의 정규 분포 난수

In [41]:
uni_rnd2 = tf.random.normal(shape=[5], mean=0.0, stddev=1.0)
tf.print(uni_rnd2)

[-1.26876068 -0.0338585451 0.811129332 -0.510175169 2.24683952]


#### 행렬 형태의 정규 분포 난수

In [44]:
normal_rnd3 = tf.random.normal(shape=[2,3], mean=0.0, stddev=1.0)
tf.print(normal_rnd3)

[[0.812847376 0.167503655 -2.26673579]
 [0.908800423 0.217198819 0.994409323]]


#### 텐서 형태의 정규 분포 난수

In [47]:
normal_rnd4 = tf.random.normal(shape=[2,3,4], mean=0.0, stddev=1.0)
tf.print(normal_rnd4)

[[[-0.446380407 -0.0842420235 0.0924355537 0.476810575]
  [-0.740701139 -0.770000517 2.139642 -0.38183102]
  [0.7803303 0.661667705 0.193060175 -0.521198273]]

 [[2.56975794 -0.16815187 0.297629744 0.212603152]
  [-0.184350729 0.394608974 -1.11678171 0.952547371]
  [0.949638247 0.466843337 -0.799134672 1.42294097]]]
